using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;

namespace WpfControlSamples.Views.AttachedProperties
{
    // DataGrid.AutoGenerateColumns=true 時に最終列の幅を最大にします
    public sealed class DataGridLastColumnStar
    {
        public static readonly DependencyProperty IsLastColumnStarProperty =
            DependencyProperty.RegisterAttached("IsLastColumnStar", typeof(bool), typeof(DataGridLastColumnStar),
                new PropertyMetadata(OnIsLastColumnStarChanged));

        public static bool GetIsLastColumnStar(DependencyObject dependencyObject) =>
            (bool)dependencyObject.GetValue(IsLastColumnStarProperty);

        public static void SetIsLastColumnStar(DependencyObject dependencyObject, bool value) =>
            dependencyObject.SetValue(IsLastColumnStarProperty, value);

        private static void OnIsLastColumnStarChanged(DependencyObject sender, DependencyPropertyChangedEventArgs e)
        {
            if (sender is not DataGrid dataGrid) return;
            if (e.NewValue is not bool newValue) return;
            if (newValue)
            {
                dataGrid.AutoGeneratedColumns += OnDataGridAutoGeneratedColumns;
            }
            else
            {
                dataGrid.AutoGeneratedColumns -= OnDataGridAutoGeneratedColumns;
            }
        }

        private static void OnDataGridAutoGeneratedColumns(object? sender, EventArgs e)
        {
            var columns = (sender as DataGrid)?.Columns;
            if (columns is null) return;
            if (columns.Count < 1) return;
            columns[^1].Width = new DataGridLength(1d, DataGridLengthUnitType.Star);
        }
    }
}
